[aws]
disabled = true

[conda]
disabled = true

[lua]
disabled = true

[battery]
disabled = true

[character]

[shell]
powershell_indicator = "\uf489"
zsh_indicator = "󰂧"
fish_indicator = "\uf739"
disabled = false
