require('packer')
require('plugins')
require('settings')

require('theme')

-- vim.cmd('source $HOME/.config/nvim/plugin/vim-terraform.vim')
-- vim.cmd('source $HOME/.config/nvim/plugin/vimwiki.vim')

-- require('lmantis.keybindings')
-- require('lmantis.cmp')
-- require('lmantis.colorizer')
-- require('lmantis.nvim-lspconfig')
-- require('lmantis.gitsigns')
-- require('lmantis.indent')
-- require('lmantis.neo-tree')
-- require('lmantis.telescope')
-- require('lmantis.todocomments')
-- require('lmantis.treesitter')
-- require('lmantis.lspsaga')
-- -- require('lmantis.truezen')
-- require('lmantis.zenmode')
