require('liquidmantis.packer')
require('plugins')
require('settings')
require('liquidmantis.keybindings')
require('liquidmantis.globals')

require('theme')


-- vim.cmd('source $HOME/.config/nvim/plugin/vim-terraform.vim')
-- vim.cmd('source $HOME/.config/nvim/plugin/vimwiki.vim')

require('liquidmantis.cmp')
require('liquidmantis.codewindow')
require('liquidmantis.colorizer')
require('liquidmantis.comment')
require('liquidmantis.gitsigns')
require('liquidmantis.harpoon')
require('liquidmantis.indent')
require('liquidmantis.leap')
require('liquidmantis.lspsaga')
require('liquidmantis.luasnip')
-- require('liquidmantis.neo-tree')
require('liquidmantis.nvimtree')
require('liquidmantis.neoclip')
require('liquidmantis.nvim-lspconfig')
require('liquidmantis.nvim-notify')
-- require('liquidmantis.telekasten')
require('liquidmantis.telescope')
require('liquidmantis.telescope-functions')
require('liquidmantis.todocomments')
require('liquidmantis.treesitter')
-- -- require('liquidmantis.truezen')
require('liquidmantis.zenmode')
require('liquidmantis.zk-nvim')
