#! /usr/bin/env sh

# save this as a file somewhere, then run:
#     chmod +x path/to/this/script
# now execute this file from your yabairc:
#    ./path/to/this/script

# if [ $# -ne 0 ]; then 
# 	for event in window_destroyed space_changed; do
# 		yabai -m signal --add label="${0}_${event}" \
# 			event="${event}" action="${0}"
# 	done
# 	exit
# fi

# { 
# 	yabai -m query --windows --window \
# 		|| yabai -m window --focus mouse 
# } > /dev/null 2>&1

sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration		   0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xaaf8cc18
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# app ignores
yabai -m rule --add app="^Contexts$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Preferences$" manage=off
yabai -m rule --add app="^Activity Monitor" manage=off
yabai -m rule --add app="^Quicken" manage=off
yabai -m rule --add app="^Stickies" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add title="^Tyme" manage=off
yabai -m rule --add title="^Hammerspoon" manage=off
yabai -m rule --add title="^Wally" manage=off
yabai -m rule --add title="^Options" manage=off
yabai -m rule --add title="^Settings$" manage=off
yabai -m rule --add title="Tabs Outliner" manage=off
yabai -m rule --add title="Tabli" manage=off
yabai -m rule --add title="FloatShell" manage=off layer=above

# app special handlers
yabai -m rule --add title="Picture in Picture" manage=off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

# events
# Contexts' sidebar and the Teams notification process seem to jump to the top of the list when their
# respective apps are running.  Exclude them from focus targets.
# focus window after active space changes
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq '. | map(select(.title != \"Sidebar\" and .title != \"Microsoft Teams Notification\")) | .[0].id' )"

# focus window after active display changes
# yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq '. | map(select(.title != \"Sidebar\" and .title != \"Microsoft Teams Notification\")) | .[0].id' )"


echo "yabai configuration loaded.."
