Modes.HyperConfig:bind('', 'p', function()
  Modes.EnterHyperConfigPadding()
  Modes.ExitHyperConfig()
end)

Modes.HyperConfig:bind('cmd', 'r', function()
  hs.reload()
end)

Modes.HyperConfig:bind('cmd', 'y', function()
  hs.notify.show('Hammerspoon', 'Reload Notification', 'Restarting Yabai.')
  Log.i(hs.execute('yabai --stop-service && yabai --start-service'))
end)

local h = hs.hotkey.modal.new()
Modes.HyperConfig:bind('', 'h', function()
  Modes.ExitHyperConfig()
  h:enter()
end)

h:bind('', 'd', function()
  Log.setLogLevel('debug')
  h:exit()
end)
h:bind('', 'i', function()
  Log.setLogLevel('info')
  h:exit()
end)
h:bind('', 'w', function()
  Log.setLogLevel('warning')
  h:exit()
end)



Modes.HyperConfigPadding:bind('', '1', function() Utils.set_padding(1, 1) end)
Modes.HyperConfigPadding:bind('', '2', function() Utils.set_padding(2, 2) end)
Modes.HyperConfigPadding:bind('', '3', function() Utils.set_padding(3, 3) end)
Modes.HyperConfigPadding:bind('', '4', function() Utils.set_padding(4, 4) end)
Modes.HyperConfigPadding:bind('', '5', function() Utils.set_padding(5, 5) end)
Modes.HyperConfigPadding:bind('', '6', function() Utils.set_padding(6, 6) end)
Modes.HyperConfigPadding:bind('', '7', function() Utils.set_padding(7, 7) end)
Modes.HyperConfigPadding:bind('', '8', function() Utils.set_padding(8, 8) end)
Modes.HyperConfigPadding:bind('', '9', function() Utils.set_padding(9, 9) end)
Modes.HyperConfigPadding:bind('', '0', function() Utils.set_padding(0, 0) end)
Modes.HyperConfigPadding:bind('', '=', function() Utils.set_padding('=', '=') end)
