[[session]]
name = "main"
path = "~"

[[session]]
name = "notes"
path = "~/notes/"
startup_command = "nvim +'ObsidianToday'"

[[session]]
name = "downloads"
path = "~/Downloads/"
startup_command = "yazi"

[[session]]
name = "dotfiles"
path = "~/git-home/dotfiles/"
startup_command = "nvim +'Telescope find_files'"

[[session]]
name = "homelab"
path = "~/git-home/homelab"
