[[session]]
name = "Notes"
path = "~/Dropbox/documents/notes/"
startup_command = "nvim inbox.md"

[[session]]
name = "Dotfiles"
path = "~/git-home/dotfiles/"
startup_command = "nvim +'Telescope find_files'"
