[[session]]
name = "main"
path = "~"

[[session]]
name = "notes"
path = "~/Dropbox/documents/notes/"
startup_command = "nvim inbox.md"

[[session]]
name = "downloads"
path = "~/Downloads/"
startup_command = "yazi"

[[session]]
name = "dotfiles"
path = "~/git-home/dotfiles/"
startup_command = "nvim +'Telescope find_files'"

