export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh 
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/local/etc/profile.d/z.sh
source ~/.config/zsh/aliases

fpath=(/usr/local/share/zsh-completions $fpath)
fpath=(/usr/local/share/zsh/site-functions$fpath)

autoload -Uz compinit && compinit -i
# az-cli uses bash completion, this loads it in zsh
autoload -U +X bashcompinit && bashcompinit
source /usr/local/etc/bash_completion.d/az


bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
bindkey -v

export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"

# remove esc delay
KEYTIMEOUT=1

export HISTORY_SUBSTRING_SEARCH_FUZZY=true
export PATH="/usr/local/sbin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
